name: exo
on: workflow_dispatch
jobs:
    job1:
        name: tester le test
        runs-on: ubuntu-latest
        outputs:
            var1: ${{steps.test.conclusion}}
        steps:
            - name: get source
              uses: actions/checkout@v4
            - name: cache npm
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: install npm
              run: npm ci
            - name: build
              run: npm run build
            - name: test
              id: test
              run: npm run test
              continue-on-error: true
    job2:
        name: récupérer le résultat
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: afficher si le test a échoué
              run: echo $RES >> $GITHUB_STEP_SUMMARY
              env:
                RES: ${{ needs.job1.outputs.var1 }}
