name: premier workflow
on: workflow_dispatch
jobs:
  premier_job:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo "Hello world"
      - name: step-2
        run: echo byebye
  deuxieme_job:
    name: job2
    needs: premier_job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Je suis un 2e job"
