name: wf on push
on: push
jobs:
    mon_job:
        name: build test run
        runs-on: ubuntu-latest
        steps:
            - name: get source
              uses: actions/checkout@v4
            - name: cache npm
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: install npm
              run: npm ci
            - name: build
              run: npm run build
            - name: test
              run: npm run test
            - name: run 
              run: npm run start
